# Based on https://github.com/matrix-org/dendrite/blob/master/.github/workflows/docker-hub.yml

name: "Docker Hub - Latest"

on:
  push:

env:
  DOCKER_NAMESPACE: halfshot
  PLATFORMS: linux/amd64
  PLATFORMS_PUSH: linux/amd64,linux/arm64
  # Only push if this is main, otherwise we just want to build
  PUSH: ${{ github.ref == 'refs/heads/main' }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  docker-latest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Build image
        uses: docker/build-push-action@v3
        if: env.PUSH == false
        with:
          context: .
          file: ./Dockerfile
          platforms: ${{ env.PLATFORMS }}
          push: false
          tags: |
            ${{ env.DOCKER_NAMESPACE }}/matrix-hookshot:latest

          # arm64 builds OOM without the git fetch setting. c.f.
          # https://github.com/rust-lang/cargo/issues/10583
          build-args: |
            CARGO_NET_GIT_FETCH_WITH_CLI=true
      - name: Build image (push)
        uses: docker/build-push-action@v3
        if: env.PUSH
        with:
          context: .
          file: ./Dockerfile
          platforms: ${{ env.PLATFORMS_PUSH }}
          push: true
          tags: |
            ${{ env.DOCKER_NAMESPACE }}/matrix-hookshot:latest

          # arm64 builds OOM without the git fetch setting. c.f.
          # https://github.com/rust-lang/cargo/issues/10583
          build-args: |
            CARGO_NET_GIT_FETCH_WITH_CLI=true