name: Contribution requirements

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  signoff:
    uses: matrix-org/matrix-appservice-bridge/.github/workflows/sign-off.yml@f32b2e8fa72d661b37e21f5edea86cc183f8482e
